export enum APIError {
  UserNotFound,
  OtherUserNotFound,
  UserIsNotYourFriend,
  UserIsNotFriendWithYou,
  InvalidColor,
  UserAlreadyInvitedToChannel,
  FriendRequestAlreadySent,
  FriendRequestNotFound,
  InvalidToken,
  UpdateFailed,
  InvalidNickname,
  NicknameAlreadyTaken,
  UserIsIntra,
  InvalidPassword,
  UserNotVerified,
  CodeSend,
}