name: ft_transcendence

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - net0
    volumes:
      - postgres:/var/lib/postgresql/data/

  client:
    container_name: ft_transcendence-client-prod
    build:
      context: ./client
      target: production
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    networks:
      - net0
    env_file:
      - client/.env.local

  api:
    container_name: ft_transcendence-api-prod
    build:
      context: ./api
      target: production
    environment:
      - API_PORT=$API_PORT
      - CLIENT_PORT=$CLIENT_PORT
      - PROTOCOL=$PROTOCOL
      - HOST_IP=$HOST_IP
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - API_UID=$API_UID
      - JWT_SECRET=$JWT_SECRET
      - API_SECRET=$API_SECRET
      - API_URL=$API_URL
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_USR=$EMAIL_USR
      - EMAIL_PWD=$EMAIL_PWD
      - EMAIL_FORM=$EMAIL_FORM
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - postgres
    networks:
      - net0

volumes:
  postgres:

networks:
  net0: {}