name: ft_transcendance

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - api/.env
    ports:
      - 5432:5432
    networks:
      - net0
    volumes:
      - postgres:/var/lib/postgresql/data/

  client:
    build: ./client
    container_name: ft_transcendance-client
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    networks:
      - net0
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REACT_APP_API_IP=$API_IP

  api:
    build: ./api
    container_name: ft_transcendance-api
    environment:
      - API_PORT=$API_PORT
      - API_DEBUG_PORT=$API_DEBUG_PORT
      - API_IP=$API_IP
    ports:
      - $API_PORT:$API_PORT
      - $API_DEBUG_PORT:$API_DEBUG_PORT
    depends_on:
      - postgres
    networks:
      - net0
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  ### Postgrey admin ###
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ft_transcendance-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - net0

volumes:
  postgres:
  pgadmin:

networks:
  net0: {}