name: ft_transcendance

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - net0
    volumes:
      - postgres:/var/lib/postgresql/data/

  client:
    container_name: ft_transcendance-client
    build:
      context: ./client
      target: development
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    networks:
      - net0
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REACT_APP_API_PORT=$API_PORT
      - REACT_APP_CLIENT_PORT=$CLIENT_PORT
      - REACT_APP_PROTOCOL=$PROTOCOL
      - REACT_APP_HOST_IP=$HOST_IP
      - REACT_APP_REDIR_URL=$REDIR_URL
      - REACT_APP_WS_PROTOCOL=$WS_PROTOCOL

  api:
    container_name: ft_transcendance-api
    build:
      context: ./api
      target: development
    command: npm run start:dev
    environment:
      - API_PORT=$API_PORT
      - CLIENT_PORT=$CLIENT_PORT
      - PROTOCOL=$PROTOCOL
      - HOST_IP=$HOST_IP
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - API_UID=$API_UID
      - JWT_SECRET=$JWT_SECRET
      - API_URL=$API_URL
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_USR=$EMAIL_USR
      - EMAIL_PWD=$EMAIL_PWD
      - EMAIL_FORM=$EMAIL_FORM
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - postgres
    networks:
      - net0
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres:
  pgadmin:

networks:
  net0: {}